apiVersion: v1
kind: Secret
metadata:
  name: jenkins-creds
  namespace: {{ .Values.controller.namespace }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.controller.jenkins_admin_user | b64enc | quote }}
  jenkins-admin-pass: {{ .Values.controller.jenkins_admin_pass | b64enc | quote }}
