apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    # nodePort: 31567
  - name: jnlp
    port: 50000
    targetPort: 50000