# Default values for vproapp 
vproapp:
  image:
    repository: dheerajlearningdocker/vprofileapp
    tag: V1
  replicacount: 1
  containerport: 8080
  portName: vproapp-port
  service:
    port: 80
    type: ClusterIP

# Enable or Disable ingress
ingress:
  enabled: true


# Default values for memcache
vpromc:
  image:
    repository: memcached
    tag: latest
  replicacount: 1
  containerport: 11211
  portName: memcache-port
  service:
    port: 11211
    type: ClusterIP

# Default values for rabbitmq
vprormq:
  image: 
    repository: rabbitmq
    tag: latest
  replicacount: 1
  containerport: 15672
  portName: rabbitmq-port
  service:
    port: 15672
    type: ClusterIP
  rmq_password: Z3Vlc3Q=
  rmq_user: "guest"


# Default values for mysql
vprodb:
  image: 
    repository: dheerajlearningdocker/vprofiledb
    tag: vprdbfix
  replicacount: 1
  containerport: 3306
  portName: vprodb-port
  service:
    port: 3306
  db_password: dnByb2RicGFzcw==
  persistance:
    storage: 3Gi